# Generated by Django 3.0.7 on 2020-06-29 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='background_color',
        ),
        migrations.RemoveField(
            model_name='event',
            name='day',
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=8)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schedule.Event')),
            ],
        ),
    ]
