# Generated by Django 3.0.7 on 2020-06-30 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20200629_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='day',
            field=models.CharField(default='day_error', max_length=9),
        ),
        migrations.DeleteModel(
            name='Day',
        ),
    ]
