# Generated by Django 3.0.7 on 2020-06-30 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_auto_20200630_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='day',
            field=models.CharField(default='day_wrong', max_length=9),
        ),
    ]
