# Generated by Django 3.0.8 on 2020-07-06 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0011_auto_20200701_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='end_time',
        ),
    ]
