# Generated by Django 3.0.8 on 2020-07-15 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0012_remove_event_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='completed',
            field=models.IntegerField(default=0),
        ),
    ]
