# Generated by Django 3.0.8 on 2020-07-15 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0013_auto_20200715_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='completed',
            field=models.BooleanField(default=0),
        ),
    ]
